// Copyright (c) 2025 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.

// Code generated by go generate; DO NOT EDIT.
// This file is generated from tools/codegen/internal/codegen.go

package mcpserver

import (
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// createResources creates and returns all MCP resources without adding them to a server.
// It also populates global cached metadata for resource handlers.
//
// This allows for easier testing of resource creation logic and resource definition validation.
//
// Returns:
//   - A slice of server.ServerResource containing all static and dynamic resources
//
// The function defines the following resources:
//   - config://template: Example configuration file for the MCP server
//   - info://version: Version and build information for the MCP server
//   - docs://certificate-formats: Documentation on supported certificate formats and usage
//   - status://server-status: Current status and health information for the MCP server
//
// These resources provide static content and metadata to MCP clients. Each resource
// includes a URI, name, description, MIME type, and handler function.
func createResources() []server.ServerResource {
	// Get server cache for storing metadata
	cache := getServerCache()
	cache.resources = make([]map[string]any, 0, 4)

	resources := []server.ServerResource{
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"config://template",
					"Server Configuration Template",
					mcp.WithResourceDescription("Example configuration file for the MCP server"),
					mcp.WithMIMEType("application/json"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 1),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "configuration", "readOnly": true})
				return res
			}(),
			Handler: handleConfigResource,
		},
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"info://version",
					"Server Version Information",
					mcp.WithResourceDescription("Version and build information for the MCP server"),
					mcp.WithMIMEType("application/json"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 0.8),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "metadata", "readOnly": true})
				return res
			}(),
			Handler: handleVersionResource,
		},
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"docs://certificate-formats",
					"Certificate Format Documentation",
					mcp.WithResourceDescription("Documentation on supported certificate formats and usage"),
					mcp.WithMIMEType("text/markdown"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 0.9),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "documentation", "readOnly": true})
				return res
			}(),
			Handler: handleCertificateFormatsResource,
		},
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"status://server-status",
					"Server Status Information",
					mcp.WithResourceDescription("Current status and health information for the MCP server"),
					mcp.WithMIMEType("application/json"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 0.7),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "monitoring", "readOnly": true})
				return res
			}(),
			Handler: handleStatusResource,
		},
	}

	// Extract metadata from created resources for resource handlers
	populateResourceMetadataCache(cache, resources)

	return resources
}
