// Copyright (c) 2026 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.

// Code generated by go generate; DO NOT EDIT.
// This file is generated from tools/codegen/internal/codegen.go

package mcpserver

import (
	"github.com/mark3labs/mcp-go/mcp"
)

// createResources creates and returns all MCP resources without adding them to a server.
// It organizes resources into two categories: those that don't require embedded filesystem
// access and those that need access to embedded templates or static files.
//
// This function generates MCP-compliant resource definitions with proper URI patterns,
// MIME types, audience restrictions, and handler bindings. Resources are categorized based on
// their embedded filesystem requirements to enable flexible server initialization.
//
// Returns:
//   - []ServerResource: Slice of server resource definitions without embed access
//   - []ServerResourceWithEmbed: Slice of server resource definitions with embed access
//
// The function defines the following resources:
//   - config://template: Example configuration file for the MCP server
//   - info://version: Version and build information for the MCP server
//   - docs://certificate-formats: Documentation on supported certificate formats and usage
//   - status://server-status: Current status and health information for the MCP server
//
// Each resource definition includes:
//   - Unique URI identifier following MCP resource naming conventions
//   - Human-readable name and description for user interfaces
//   - MIME type specification for proper content handling
//   - Audience restrictions and priority settings for access control
//   - Metadata tags for categorization and discovery
//   - Handler functions that generate or serve the resource content
func createResources() ([]ServerResource, []ServerResourceWithEmbed) {
	// Resources that don't need embed access
	resources := []ServerResource{
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"config://template",
					"Server Configuration Template",
					mcp.WithResourceDescription("Example configuration file for the MCP server"),
					mcp.WithMIMEType("application/json"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 1),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "configuration", "readOnly": true})
				return res
			}(),
			Handler: handleConfigResource,
		},
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"info://version",
					"Server Version Information",
					mcp.WithResourceDescription("Version and build information for the MCP server"),
					mcp.WithMIMEType("application/json"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 0.8),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "metadata", "readOnly": true})
				return res
			}(),
			Handler: handleVersionResource,
		},
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"status://server-status",
					"Server Status Information",
					mcp.WithResourceDescription("Current status and health information for the MCP server"),
					mcp.WithMIMEType("application/json"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 0.7),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "monitoring", "readOnly": true})
				return res
			}(),
			Handler: handleStatusResource,
		},
	}

	// Resources that need embed access
	resourcesWithEmbed := []ServerResourceWithEmbed{
		{
			Resource: func() mcp.Resource {
				res := mcp.NewResource(
					"docs://certificate-formats",
					"Certificate Format Documentation",
					mcp.WithResourceDescription("Documentation on supported certificate formats and usage"),
					mcp.WithMIMEType("text/markdown"),
					mcp.WithAnnotations(
						[]mcp.Role{
							mcp.RoleUser,
							mcp.RoleAssistant,
						}, 0.9),
				)
				res.Meta = mcp.NewMetaFromMap(map[string]any{"category": "documentation", "readOnly": true})
				return res
			}(),
			Handler: handleCertificateFormatsResource,
		},
	}

	return resources, resourcesWithEmbed
}
