// Copyright (c) 2025 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.

// Code generated by go generate; DO NOT EDIT.
// This file is generated from tools/codegen/internal/codegen.go

package mcpserver

import (
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// createResources creates and returns all MCP resources without adding them to a server.
// This allows for easier testing of resource creation logic and resource definition validation.
//
// Returns:
//   - A slice of server.ServerResource containing all static and dynamic resources
//
// The function defines the following resources:
//   - config://template: Example configuration file for the MCP server
//   - info://version: Version and build information for the MCP server
//   - docs://certificate-formats: Documentation on supported certificate formats and usage
//   - status://server-status: Current status and health information for the MCP server
//
// These resources provide static content and metadata to MCP clients. Each resource
// includes a URI, name, description, MIME type, and handler function.
func createResources() []server.ServerResource {
	return []server.ServerResource{
		{
			Resource: mcp.NewResource(
				"config://template",
				"Server Configuration Template",
				mcp.WithResourceDescription("Example configuration file for the MCP server"),
				mcp.WithMIMEType("application/json"),
			),
			Handler: handleConfigResource,
		},
		{
			Resource: mcp.NewResource(
				"info://version",
				"Server Version Information",
				mcp.WithResourceDescription("Version and build information for the MCP server"),
				mcp.WithMIMEType("application/json"),
			),
			Handler: handleVersionResource,
		},
		{
			Resource: mcp.NewResource(
				"docs://certificate-formats",
				"Certificate Format Documentation",
				mcp.WithResourceDescription("Documentation on supported certificate formats and usage"),
				mcp.WithMIMEType("text/markdown"),
			),
			Handler: handleCertificateFormatsResource,
		},
		{
			Resource: mcp.NewResource(
				"status://server-status",
				"Server Status Information",
				mcp.WithResourceDescription("Current status and health information for the MCP server"),
				mcp.WithMIMEType("application/json"),
			),
			Handler: handleStatusResource,
		},
	}
}
