// Copyright (c) 2025 H0llyW00dzZ All rights reserved.
//
// By accessing or using this software, you agree to be bound by the terms
// of the License Agreement, which you can find at LICENSE files.

// Code generated by go generate; DO NOT EDIT.
// This file is generated from tools/codegen/internal/codegen.go

package mcpserver

import (
	"github.com/mark3labs/mcp-go/mcp"
)

// Tool names as constants for consistency and type safety.
const (
	// ToolResolveCertChain resolves a single X509 certificate chain from file or base64 data.
	// Used for building complete certificate chains from leaf certificates.
	ToolResolveCertChain = "resolve_cert_chain"

	// ToolValidateCertChain validates a certificate chain for correctness and trust.
	// Performs comprehensive chain validation including signature verification and trust path validation.
	ToolValidateCertChain = "validate_cert_chain"

	// ToolBatchResolveCertChain processes multiple certificate chains in a single operation.
	// Optimizes performance for bulk certificate processing scenarios.
	ToolBatchResolveCertChain = "batch_resolve_cert_chain"

	// ToolCheckCertExpiry monitors certificate expiration dates with configurable warning thresholds.
	// Essential for certificate lifecycle management and renewal planning.
	ToolCheckCertExpiry = "check_cert_expiry"

	// ToolFetchRemoteCert retrieves certificate chains from remote TLS endpoints.
	// Enables analysis of server certificates without local file access.
	ToolFetchRemoteCert = "fetch_remote_cert"

	// ToolAnalyzeCertificateWithAI performs advanced certificate analysis using AI collaboration.
	// Provides security assessments, compliance checks, and actionable recommendations.
	ToolAnalyzeCertificateWithAI = "analyze_certificate_with_ai"

	// ToolGetResourceUsage provides server resource usage statistics and CRL cache metrics.
	// Includes memory usage, GC statistics, and performance monitoring data.
	ToolGetResourceUsage = "get_resource_usage"

	// ToolVisualizeCertChain provides certificate chain visualization in multiple formats.
	// Supports ASCII tree, markdown table, and JSON output for better certificate chain analysis.
	ToolVisualizeCertChain = "visualize_cert_chain"
)

// Tool roles as constants for consistency and type safety.
const (
	// RoleChainResolver handles single certificate chain resolution operations.
	// Responsible for building complete certificate chains from leaf certificates.
	RoleChainResolver = "chainResolver"

	// RoleChainValidator performs certificate chain validation and trust verification.
	// Ensures certificate chains meet security and correctness requirements.
	RoleChainValidator = "chainValidator"

	// RoleBatchResolver manages bulk certificate chain processing operations.
	// Optimizes performance for high-volume certificate processing scenarios.
	RoleBatchResolver = "batchResolver"

	// RoleExpiryChecker monitors certificate expiration dates and renewal requirements.
	// Critical for certificate lifecycle management and preventing outages.
	RoleExpiryChecker = "expiryChecker"

	// RoleRemoteFetcher retrieves certificate chains from remote TLS endpoints.
	// Enables analysis of server certificates without requiring local file access.
	RoleRemoteFetcher = "remoteFetcher"

	// RoleAIAnalyzer performs advanced certificate analysis using AI collaboration.
	// Provides intelligent security assessments and actionable recommendations.
	RoleAIAnalyzer = "aiAnalyzer"

	// RoleResourceMonitor tracks server resource usage and performance metrics.
	// Provides insights into memory usage, GC statistics, and CRL cache efficiency.
	RoleResourceMonitor = "resourceMonitor"

	// RoleChainVisualizer provides certificate chain visualization capabilities.
	// Supports multiple output formats for enhanced certificate analysis and debugging.
	RoleChainVisualizer = "chainVisualizer"
)

// createTools creates and returns all MCP tool definitions with their handlers.
// It organizes tools into two categories: those that don't require configuration
// and those that need access to the server configuration (e.g., for AI integration or timeouts).
//
// This function generates MCP-compliant tool definitions with proper parameter validation,
// type constraints, and handler bindings. Tools are categorized based on their
// configuration requirements to enable flexible server initialization.
//
// Returns:
//   - []ToolDefinition: Slice of tool definitions for tools without config dependencies
//   - []ToolDefinitionWithConfig: Slice of tool definitions for tools that require server configuration
//
// Tool Categories:
//   - Standard tools ([]ToolDefinition): resolve_cert_chain, validate_cert_chain, batch_resolve_cert_chain,
//     get_resource_usage, visualize_cert_chain
//   - Config-dependent tools ([]ToolDefinitionWithConfig): check_cert_expiry, fetch_remote_cert, analyze_certificate_with_ai
//
// The function defines the following tools:
//   - resolve_cert_chain: Resolve X509 certificate chain from a certificate file or base64-encoded certificate data
//   - validate_cert_chain: Validate a X509 certificate chain for correctness and trust
//   - batch_resolve_cert_chain: Resolve X509 certificate chains for multiple certificates in batch
//   - check_cert_expiry: Check certificate expiry dates and warn about upcoming expirations
//   - fetch_remote_cert: Fetch X509 certificate chain from a remote hostname/port
//   - analyze_certificate_with_ai: Analyze certificate data using AI collaboration (requires bidirectional communication)
//   - get_resource_usage: Get current resource usage statistics including memory, GC, and CPU information
//   - visualize_cert_chain: Visualize certificate chain in multiple formats (ASCII tree, table, JSON)
//
// Each tool definition includes:
//   - MCP parameter specifications with type validation and constraints
//   - Comprehensive descriptions for user interface display
//   - MCP annotations for tool behavior hints (read-only, destructive, etc.)
//   - Proper handler function bindings for tool execution
func createTools() ([]ToolDefinition, []ToolDefinitionWithConfig) {
	// Tools that don't need config
	tools := []ToolDefinition{
		{
			Tool: mcp.NewTool(
				ToolResolveCertChain,
				mcp.WithDescription("Resolve X509 certificate chain from a certificate file or base64-encoded certificate data"),
				mcp.WithReadOnlyHintAnnotation(true),
				mcp.WithIdempotentHintAnnotation(true),

				mcp.WithString(
					"certificate",
					mcp.Required(),
					mcp.Description("Certificate file path or base64-encoded certificate data"),
					mcp.MinLength(1),
				),

				mcp.WithString(
					"format",
					mcp.Description("Output format: 'pem', 'der', or 'json' (default: pem)"),
					mcp.Enum("pem", "der", "json"),
					mcp.DefaultString("pem"),
				),

				mcp.WithBoolean(
					"include_system_root",
					mcp.Description("Include system root CA in output (default: false)"),
					mcp.DefaultBool(false),
				),

				mcp.WithBoolean(
					"intermediate_only",
					mcp.Description("Output only intermediate certificates (default: false)"),
					mcp.DefaultBool(false),
				),
			),
			Handler: handleResolveCertChain,
			Role:    RoleChainResolver,
		},
		{
			Tool: mcp.NewTool(
				ToolValidateCertChain,
				mcp.WithDescription("Validate a X509 certificate chain for correctness and trust"),

				mcp.WithString(
					"certificate",
					mcp.Required(),
					mcp.Description("Certificate file path or base64-encoded certificate data"),
				),

				mcp.WithBoolean(
					"include_system_root",
					mcp.Description("Include system root CA for validation (default: true)"),
					mcp.DefaultBool(true),
				),
			),
			Handler: handleValidateCertChain,
			Role:    RoleChainValidator,
		},
		{
			Tool: mcp.NewTool(
				ToolBatchResolveCertChain,
				mcp.WithDescription("Resolve X509 certificate chains for multiple certificates in batch"),

				mcp.WithString(
					"certificates",
					mcp.Required(),
					mcp.Description("Comma-separated list of certificate file paths or base64-encoded certificate data"),
				),

				mcp.WithString(
					"format",
					mcp.Description("Output format: 'pem', 'der', or 'json' (default: pem)"),
					mcp.DefaultString("pem"),
				),

				mcp.WithBoolean(
					"include_system_root",
					mcp.Description("Include system root CA in output (default: false)"),
					mcp.DefaultBool(false),
				),

				mcp.WithBoolean(
					"intermediate_only",
					mcp.Description("Output only intermediate certificates (default: false)"),
					mcp.DefaultBool(false),
				),
			),
			Handler: handleBatchResolveCertChain,
			Role:    RoleBatchResolver,
		},
		{
			Tool: mcp.NewTool(
				ToolGetResourceUsage,
				mcp.WithDescription("Get current resource usage statistics including memory, GC, and CPU information"),

				mcp.WithBoolean(
					"detailed",
					mcp.Description("Include detailed memory breakdown (default: false)"),
					mcp.DefaultBool(false),
				),

				mcp.WithString(
					"format",
					mcp.Description("Output format: 'json' or 'markdown' (default: 'json')"),
					mcp.Enum("json", "markdown"),
					mcp.DefaultString("json"),
				),
			),
			Handler: handleGetResourceUsage,
			Role:    RoleResourceMonitor,
		},
		{
			Tool: mcp.NewTool(
				ToolVisualizeCertChain,
				mcp.WithDescription("Visualize certificate chain in multiple formats (ASCII tree, table, JSON)"),
				mcp.WithReadOnlyHintAnnotation(true),
				mcp.WithIdempotentHintAnnotation(true),

				mcp.WithString(
					"certificate",
					mcp.Required(),
					mcp.Description("Certificate file path or base64-encoded certificate data"),
					mcp.MinLength(1),
				),

				mcp.WithString(
					"format",
					mcp.Description("Output format: 'ascii', 'table', or 'json' (default: ascii)"),
					mcp.Enum("ascii", "table", "json"),
					mcp.DefaultString("ascii"),
				),
			),
			Handler: handleVisualizeCertChain,
			Role:    RoleChainVisualizer,
		},
	}

	// Tools that need config
	toolsWithConfig := []ToolDefinitionWithConfig{
		{
			Tool: mcp.NewTool(
				ToolCheckCertExpiry,
				mcp.WithDescription("Check certificate expiry dates and warn about upcoming expirations"),
				mcp.WithReadOnlyHintAnnotation(true),
				mcp.WithIdempotentHintAnnotation(true),

				mcp.WithString(
					"certificate",
					mcp.Required(),
					mcp.Description("Certificate file path or base64-encoded certificate data"),
					mcp.MinLength(1),
				),

				mcp.WithNumber(
					"warn_days",
					mcp.Description("Number of days before expiry to show warning (default: 30)"),
					mcp.Min(1),
					mcp.Max(365),
					mcp.DefaultNumber(30),
				),
			),
			Handler: handleCheckCertExpiry,
			Role:    RoleExpiryChecker,
		},
		{
			Tool: mcp.NewTool(
				ToolFetchRemoteCert,
				mcp.WithDescription("Fetch X509 certificate chain from a remote hostname/port"),

				mcp.WithString(
					"hostname",
					mcp.Required(),
					mcp.Description("Remote hostname to connect to"),
				),

				mcp.WithNumber(
					"port",
					mcp.Description("Port number (default: 443)"),
					mcp.Min(1),
					mcp.DefaultNumber(443),
				),

				mcp.WithString(
					"format",
					mcp.Description("Output format: 'pem', 'der', or 'json' (default: pem)"),
					mcp.DefaultString("pem"),
				),

				mcp.WithBoolean(
					"include_system_root",
					mcp.Description("Include system root CA in output (default: false)"),
					mcp.DefaultBool(false),
				),

				mcp.WithBoolean(
					"intermediate_only",
					mcp.Description("Output only intermediate certificates (default: false)"),
					mcp.DefaultBool(false),
				),
			),
			Handler: handleFetchRemoteCert,
			Role:    RoleRemoteFetcher,
		},
		{
			Tool: mcp.NewTool(
				ToolAnalyzeCertificateWithAI,
				mcp.WithDescription("Analyze certificate data using AI collaboration (requires bidirectional communication)"),

				mcp.WithString(
					"certificate",
					mcp.Required(),
					mcp.Description("Certificate file path or base64-encoded certificate data to analyze"),
				),

				mcp.WithString(
					"analysis_type",
					mcp.Required(),
					mcp.Description("Type of analysis (required): 'security', 'compliance', 'general'"),
					mcp.Enum("general", "security", "compliance"),
				),
			),
			Handler: handleAnalyzeCertificateWithAI,
			Role:    RoleAIAnalyzer,
		},
	}

	return tools, toolsWithConfig
}
